require ('plugins')
require ('keymaps')
require ('settings')

--Plugins config
require ('plugins-config/bufferline')
require ('plugins-config/lualine')
require ('plugins-config/dashboard')
require ('plugins-config/treesitter')
require ('plugins-config/gruvbox')
require ('plugins-config/auto-save')
require ('plugins-config/formatter')
require ('plugins-config/indent-line')
require ('plugins-config/autopairs')
require ('plugins-config/init')
require ('nv-compe/compe')
require ('nvim_lsp/init')
--Vim source
--vim.cmd('source ~/appdata/local/nvim/coc-config.vim')
