require ('plugins')
require ('keymaps')
require ('settings')
require ('plugins-config')

--Plugins config
require ('plugins-config/autopairs')
require ('plugins-config/bufferline')
require ('plugins-config/lualine')
require ('plugins-config/dashboard')
require ('plugins-config/nvimTree')
require ('plugins-config/theme')
require ('plugins-config/treesitter')
require ('plugins-config/gruvbox')
require ('plugins-config/registers')
require ('plugins-config/auto-save')
require ('plugins-config/formatter')
require ('plugins-config/neogit')
--broken require ('plugins-config/lsp-install')

